### ISSUE TITLE
Push README and Dockerfile to DockerHub using GH Action

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sbcp-mongo#3]

**Comment by thomasyu888** [comment]
https://github.com/marketplace/actions/docker-hub-description

**Comment by tschaffter** [comment]
https://github.com/peter-evans/dockerhub-description/issues/2#issue-484960493

**Comment by thomasyu888** [comment]
Done, the team now has admin permission on the repo

**Comment by tschaffter** [comment]
README has been successfully pushed
